// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xitaso_Webapplikation.Data;

namespace Xitaso_Webapplikation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210701200950_addAnalysenToDatabase")]
    partial class addAnalysenToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Analyse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjektId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("Analyse");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Analysekategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnalyseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnalyseId");

                    b.ToTable("Analysekategorie");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Frage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnalysekategorieId")
                        .HasColumnType("int");

                    b.Property<int>("IstBewertung")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SollBewertung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysekategorieId");

                    b.ToTable("Frage");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProjectFinished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Analyse", b =>
                {
                    b.HasOne("Xitaso_Webapplikation.Models.Projekt", null)
                        .WithMany("Analysis")
                        .HasForeignKey("ProjektId");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Analysekategorie", b =>
                {
                    b.HasOne("Xitaso_Webapplikation.Models.Analyse", null)
                        .WithMany("Analysekategories")
                        .HasForeignKey("AnalyseId");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Frage", b =>
                {
                    b.HasOne("Xitaso_Webapplikation.Models.Analysekategorie", null)
                        .WithMany("Questions")
                        .HasForeignKey("AnalysekategorieId");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Analyse", b =>
                {
                    b.Navigation("Analysekategories");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Analysekategorie", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Xitaso_Webapplikation.Models.Projekt", b =>
                {
                    b.Navigation("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
